//
//  RZZBaseViewModel.swift
//  DouYuZB
//
//  Created by renzhizhong on 2019/1/7.
//  Copyright © 2019 rzz. All rights reserved.
//

import UIKit

class RZZBaseViewModel {
    lazy var anchorGroups : [RZZAchorGroup] = [RZZAchorGroup]()

}

extension RZZBaseViewModel {
    func loadAnchorData(URLString : String, parameters : [String : Any]? = nil, finishCallBack : @escaping () -> ()) {
        let resultData : [String : Any] = ["error" : 0,"data" : [
            ["tag_name" : "魔兽世界", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "王者荣耀", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "穿越火线", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "地下城", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "QQ飞车", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "绝地求生", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "斗地主", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "足球世界", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ],
            ["tag_name" : "大话西游", "icon_url" : "https://cs-op.douyucdn.cn/dycatr/game_cate/f779aaa7554c44c8f0e43e2845a8683e.png", "room_list" : [
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311],
                ["room_id" : 19002,
                 "vertical_src" : "https://rpic.douyucdn.cn/asrpic/190105/19002_1731.jpg/dy1",
                 "is_vertical" : 0,
                 "room_name" : "DOTA2好汉杯淘汰赛",
                 "nickname" : "imbadota2频道",
                 "online" : 232311]]
            ]
            ]]
        RZZNetWorkTools.requestDta(urlString: URLString, method: .GET, parameters: parameters) { (result) in
            //1.对结果处理
            guard let dataArray = resultData["data"] as? [[String : NSObject]] else { return }
            for dict in dataArray {
                self.anchorGroups.append(RZZAchorGroup(dict : dict))
            }
            finishCallBack()
        }
    }
}
